"""Reject files and text that should not enter the source repository."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TEXT_SUFFIXES = {
    ".cfg",
    ".css",
    ".html",
    ".ini",
    ".js",
    ".json",
    ".md",
    ".py",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
}
BLOCKED_DIRS = {
    ".cache",
    ".venv",
    "artifacts",
    "data",
    "models",
    "outputs",
    "runs",
    "wandb",
}
BLOCKED_SUFFIXES = {
    ".avi",
    ".bin",
    ".ckpt",
    ".db",
    ".jpeg",
    ".jpg",
    ".jsonl",
    ".mkv",
    ".mov",
    ".mp3",
    ".mp4",
    ".npy",
    ".npz",
    ".onnx",
    ".parquet",
    ".pem",
    ".pickle",
    ".pkl",
    ".pt",
    ".pth",
    ".safetensors",
    ".sqlite",
    ".sqlite3",
    ".tar",
    ".wav",
    ".webm",
    ".zip",
}
TEXT_PATTERNS = {
    "absolute Windows path": re.compile(r"(?<![A-Za-z0-9])[A-Za-z]:[\\/]"),
    "user home path": re.compile(r"(?:C:[\\/]Users[\\/]|/Users/|/home/)"),
    "OpenAI-style secret": re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b"),
    "Google-style secret": re.compile(r"\bAIza[A-Za-z0-9_-]{20,}\b"),
    "GitHub token": re.compile(r"\b(?:ghp_|github_pat_)[A-Za-z0-9_]{20,}\b"),
    "internal result directory": re.compile(r"\b(?:runs_corl|icra_strong_accept)\b", re.I),
    "generated-code marker": re.compile(r"\b(?:generated by ChatGPT|as an AI language model|Codex-generated)\b", re.I),
}


def audit(root: Path, max_bytes: int) -> list[str]:
    findings: list[str] = []
    own_path = Path(__file__).resolve()
    for path in sorted(root.rglob("*")):
        if ".git" in path.parts or path.is_dir():
            continue
        if path.resolve() == own_path:
            continue
        relative = path.relative_to(root)
        lowered_parts = {part.lower() for part in relative.parts[:-1]}
        if lowered_parts & BLOCKED_DIRS:
            findings.append(f"blocked directory: {relative}")
        if path.suffix.lower() in BLOCKED_SUFFIXES:
            findings.append(f"blocked file type: {relative}")
        size = path.stat().st_size
        if size > max_bytes:
            findings.append(f"file exceeds {max_bytes} bytes: {relative}")
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for label, pattern in TEXT_PATTERNS.items():
            if pattern.search(text):
                findings.append(f"{label}: {relative}")
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--max-file-mb", type=float, default=25.0)
    args = parser.parse_args()
    root = args.root.resolve()
    findings = audit(root, max_bytes=int(args.max_file_mb * 1024 * 1024))
    if findings:
        print("\n".join(findings))
        return 1
    print(f"Release safety check passed: {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
